### ISSUE TITLE
[BUG] Python import error in UI

### ISSUE THREAD

**Issue by abargst** [bunkerity/bunkerweb#2495]
### What happened?

Startup of the Bunkerweb UI fails due to a python import error.

### How to reproduce?

Fresh Bunkerweb 1.6.2 install on EL9

### Configuration file(s) (yaml or .env)

```YAML

```

### Relevant log output

```shell
[2025-07-08 11:04:09 +0200] [UI] [21758] [ℹ️ ] - Starting gunicorn 23.0.0
[2025-07-08 11:04:09 +0200] [UI] [21758] [ℹ️ ] - Flask secret successfully loaded from the file.
[2025-07-08 11:04:09 +0200] [UI] [21758] [ℹ️ ] - The FLASK_SECRET environment variable has not changed since the last restart.
[2025-07-08 11:04:09 +0200] [UI] [21758] [ℹ️ ] - Flask secret securely stored.
[2025-07-08 11:04:09 +0200] [UI] [21758] [ℹ️ ] - Flask secret hash securely stored for change detection.
[2025-07-08 11:04:09 +0200] [UI] [21758] [ℹ️ ] - TOTP secrets successfully loaded from the file.
[2025-07-08 11:04:09 +0200] [UI] [21758] [ℹ️ ] - The TOTP_SECRETS environment variable has not changed since the last restart.
[2025-07-08 11:04:09 +0200] [UI] [21758] [ℹ️ ] - TOTP secrets securely stored.
[2025-07-08 11:04:09 +0200] [UI] [21758] [ℹ️ ] - TOTP environment hash securely stored for change detection.
[2025-07-08 11:04:09 +0200] [UI] [21758] [ℹ️ ] - Valid Biscuit keys successfully loaded from files.
[2025-07-08 11:04:09 +0200] [UI] [21758] [ℹ️ ] - The Biscuit keys have not changed since the last restart.
[2025-07-08 11:04:09 +0200] [UI] [21758] [ℹ️ ] - Biscuit keys securely stored.
[2025-07-08 11:04:09 +0200] [UI] [21758] [ℹ️ ] - Biscuit key hashes securely stored for change detection.
[2025-07-08 11:04:09 +0200] [UI] [21758] [ℹ️ ] - ✅ Database connection established
[2025-07-08 11:04:09 +0200] [UI] [21758] [ℹ️ ] - UI will disconnect users that have their IP address changed during a session.
[2025-07-08 11:04:09 +0200] [UI] [21758] [ℹ️ ] - Stopping temporary UI...
[2025-07-08 11:04:10 +0200] [UI] [21758] [ℹ️ ] - Temporary UI is stopped
[2025-07-08 11:04:10 +0200] [UI] [21758] [ℹ️ ] - UI is ready
[2025-07-08 11:04:10 +0200] [UI] [21758] [ℹ️ ] - Listening at: http://127.0.0.1:7000 (21758)
[2025-07-08 11:04:10 +0200] [UI] [21758] [ℹ️ ] - Using worker: gthread
[2025-07-08 11:04:10 +0200] [UI] [21762] [ℹ️ ] - Booting worker with pid: 21762
[2025-07-08 11:04:10 +0200] [UI] [21763] [ℹ️ ] - Booting worker with pid: 21763
[2025-07-08 11:04:10 +0200] [UI] [21762] [❌] - Exception in worker process
Traceback (most recent call last):
  File "/usr/share/bunkerweb/deps/python/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/usr/share/bunkerweb/deps/python/gunicorn/workers/gthread.py", line 94, in init_process
    super().init_process()
  File "/usr/share/bunkerweb/deps/python/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/share/bunkerweb/deps/python/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/share/bunkerweb/deps/python/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/share/bunkerweb/deps/python/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/usr/share/bunkerweb/deps/python/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/share/bunkerweb/deps/python/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/share/bunkerweb/ui/main.py", line 30, in <module>
    from app.models.biscuit import BiscuitMiddleware
  File "/usr/share/bunkerweb/ui/app/models/biscuit.py", line 1, in <module>
    from datetime import UTC, datetime
ImportError: cannot import name 'UTC' from 'datetime' (/usr/lib64/python3.9/datetime.py)
[2025-07-08 11:04:10 +0200] [UI] [21762] [ℹ️ ] - Worker exiting (pid: 21762)
[2025-07-08 11:04:10 +0200] [UI] [21763] [❌] - Exception in worker process
Traceback (most recent call last):
  File "/usr/share/bunkerweb/deps/python/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/usr/share/bunkerweb/deps/python/gunicorn/workers/gthread.py", line 94, in init_process
    super().init_process()
  File "/usr/share/bunkerweb/deps/python/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/share/bunkerweb/deps/python/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/share/bunkerweb/deps/python/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/share/bunkerweb/deps/python/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/usr/share/bunkerweb/deps/python/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/share/bunkerweb/deps/python/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/share/bunkerweb/ui/main.py", line 30, in <module>
    from app.models.biscuit import BiscuitMiddleware
  File "/usr/share/bunkerweb/ui/app/models/biscuit.py", line 1, in <module>
    from datetime import UTC, datetime
ImportError: cannot import name 'UTC' from 'datetime' (/usr/lib64/python3.9/datetime.py)
[2025-07-08 11:04:10 +0200] [UI] [21763] [ℹ️ ] - Worker exiting (pid: 21763)
[2025-07-08 11:04:10 +0200] [UI] [21765] [ℹ️ ] - Booting worker with pid: 21765
[2025-07-08 11:04:10 +0200] [UI] [21765] [❌] - Exception in worker process
Traceback (most recent call last):
  File "/usr/share/bunkerweb/deps/python/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/usr/share/bunkerweb/deps/python/gunicorn/workers/gthread.py", line 94, in init_process
    super().init_process()
  File "/usr/share/bunkerweb/deps/python/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/share/bunkerweb/deps/python/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/share/bunkerweb/deps/python/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/share/bunkerweb/deps/python/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/usr/share/bunkerweb/deps/python/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/share/bunkerweb/deps/python/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/share/bunkerweb/ui/main.py", line 30, in <module>
    from app.models.biscuit import BiscuitMiddleware
  File "/usr/share/bunkerweb/ui/app/models/biscuit.py", line 1, in <module>
    from datetime import UTC, datetime
ImportError: cannot import name 'UTC' from 'datetime' (/usr/lib64/python3.9/datetime.py)
[2025-07-08 11:04:10 +0200] [UI] [21765] [ℹ️ ] - Worker exiting (pid: 21765)
[2025-07-08 11:04:10 +0200] [UI] [21758] [❌] - Worker (pid:21762) exited with code 3
[2025-07-08 11:04:10 +0200] [UI] [21758] [❌] - Worker (pid:21765) was sent SIGTERM!
[2025-07-08 11:04:10 +0200] [UI] [21758] [❌] - Worker (pid:21763) was sent SIGTERM!
[2025-07-08 11:04:11 +0200] [UI] [21758] [❌] - Shutting down: Master
[2025-07-08 11:04:11 +0200] [UI] [21758] [❌] - Reason: Worker failed to boot.
```

### BunkerWeb version

1.6.2

### What integration are you using?

Linux

### Linux distribution (if applicable)

Oracle Linux 9

### Removed private data

- [x] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by abargst** [comment]
1.6.1 works - so it must be something in 1.6.2

**Comment by Michal-Koeckeis-Fresel** [comment]
This error occurs because UTC was added to the datetime module in Python 3.11, but you're running Python 3.9.

So it worked on 1.6.1 with Oracle Linux 9? 
Or did you use another distribution for 1.6.1?

**Comment by Michal-Koeckeis-Fresel** [comment]
This would be a fix for the UTC import:


```
import sys

# Check Python version to determine correct UTC import method
# UTC was added to datetime module in Python 3.11, so we need
# backwards compatibility for older Python versions
if sys.version_info >= (3, 11):
    # Python 3.11+ has UTC directly available in datetime module
    from datetime import UTC
else:
    # Python 3.9-3.10 requires using timezone.utc instead
    from datetime import timezone
    # Create UTC alias pointing to timezone.utc for compatibility
    UTC = timezone.utc
```

**Comment by TheophileDiot** [comment]
Hi @abargst, thank you for reporting this. A hotfix is in preparation

**Comment by abargst** [comment]
Just installed the fixed version. Works perfectly!
